[storage]
db_path = "boros.db"

[server]
listen_address="0.0.0.0:50052"

[peer_manager]
peers = [
    "Node:3001",
    "Node:3001",
]

[monitor]
# old tx inflight will be retried when reach a value bigger than retry_slot_diff
retry_slot_diff = 1000

[u5c]
uri = "https://mainnet.utxorpc-v0.demeter.run"

# metadata is optional
[u5c.metadata]
"dmtr-api-key" = "your key"
