[package]
name = "grcp_client"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.3"
utxorpc = "0.10.0"
